#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Create psdb database on /db2data2,/db2data3,/db2data4,/db2data1

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner and not as root" 1>&2
   exit 1
fi

if [[ "`hostname -s`" != "hadr01" ]]; then
   echo "This script must be run from hadr01" 1>&2
   exit 1
fi

echo "Creating db2 pureScale shared database"
db2 create database psdb on /db2data2,/db2data3,/db2data4 DBPATH ON /db2data1
