#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Monitor HADR

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner and not as root" 1>&2
   exit 1
fi

db2pd -db psdb -hadr | egrep "_HOST|HADR_ROLE|HADR_FLAGS|CONNECT_STATUS|_STATE|LOG_STREAM_ID|^$|PRIMARY_MEMBER"
