#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Apply DB2 license

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

IPFILE=/root/bin/backup/hadr.txt
LICHOME=/home/db2psc/pot_purescale/01setup/lic
IPLINE=`sed -n 1p $IPFILE`
ARRAY=($IPLINE)
HOSTNAM=${ARRAY[3]}
SHORTNM=${HOSTNAM%%.*}
NODENM=`hostname -s`

########################################################
i=0
while read a b c d
do
  SHORTNM=${d%%.*}
  servers[$i]=$SHORTNM
  ((i++))
done < $IPFILE
########################################################

########################################################
echo "Show license status"
for ((i = 0; i < ${#servers[@]}; ++i));
do
  server=${servers[$i]};
  ssh $server "su -l db2psc -c \"db2licm -l\""
  ssh $server "samlicm -s"
done
########################################################
echo "Apply db2 license"
for ((i = 0; i < ${#servers[@]}; ++i));
do
  server=${servers[$i]};
  ssh $server "su -l db2psc -c \"db2licm -a $LICHOME/db2de.lic\""
  ssh $server "samlicm -i $LICHOME/sam32.lic"
done
########################################################
echo "Show license status"
for ((i = 0; i < ${#servers[@]}; ++i));
do
  server=${servers[$i]};
  ssh $server "su -l db2psc -c \"db2licm -l\""
  ssh $server "samlicm -s"
done
########################################################
