#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Set up cluster level HADR parameters for primary

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner and not as root" 1>&2
   exit 1
fi

if [[ "`hostname -s`" != "hadr01" ]]; then
   echo "This script must be run from hadr01" 1>&2
   exit 1
fi

echo "Set up HADR DB CFG parameters"

db2 -v "update db cfg for psdb using HADR_TARGET_LIST 	
          {192.168.142.13:57780|192.168.142.14:57781}"
db2 -v "update db cfg for psdb using HADR_REMOTE_HOST 	
          {192.168.142.13:57780|192.168.142.14:57781}"
db2 -v "update db cfg for psdb using HADR_REMOTE_INST 	db2psc"
db2 -v "update db cfg for psdb using HADR_SYNCMODE 	ASYNC"
