#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Create db2dsdriver.cfg for CLP scripts for WLB

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner" 1>&2
   exit 1
fi


if [[ "`hostname -s`" != "node01" ]]; then
   echo "This script must be run from node01" 1>&2
   exit 1
fi

echo "Create ~/sqllib/cfg/db2dsdriver.cfg which has enableWLB=true"
cat > ~/sqllib/cfg/db2dsdriver.cfg << "EOF"
<configuration>
  <dsncollection>
    <dsn alias="PSDB" name="PSDB" host="192.168.142.102" port="50001"/>
  </dsncollection>
  <databases>
     <database name="PSDB" host="192.168.142.102" port="50001">
       <wlb>
          <parameter name="enableWLB" value="true"/>
       </wlb>
     </database>
  </databases>
</configuration>
EOF
