#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Client affinity and ACR for non-Java clients

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner" 1>&2
   exit 1
fi


if [[ "`hostname -s`" != "node01" ]]; then
   echo "This script must be run from node01" 1>&2
   exit 1
fi

echo Create db2dsdriver.cfg for Client Affinity

cat > ~/sqllib/cfg/db2dsdriver.cfg << "EOF"
<configuration>
  <dsncollection>
    <dsn alias="PSDB" name="PSDB" host="192.168.142.102" port="50001"/>
  </dsncollection>
  <databases>
     <database name="PSDB" host="192.168.142.102" port="50001">
       <acr>
	  <parameter name="enableAcr" value="true"/>
	  <parameter name="enableSeamlessAcr" value="true"/>
	  <alternateserverlist>
	     <server name="server01" hostname="192.168.142.104" port="50001"/>
	     <server name="server02" hostname="192.168.142.103" port="50001"/>
	  </alternateserverlist>
	  <affinitylist>
	     <list name="CLP01" serverorder="server01,server02"></list>
	  </affinitylist>
	  <clientaffinitydefined>
	     <client name="CLP" hostname="192.168.142.101" listname="CLP01"/>
	  </clientaffinitydefined>
       </acr>
     </database>
  </databases>
</configuration>
EOF

echo -e "Client Affinity in db2dsdriver.cfg created in ~/sqllib/cfg"
