#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Catalog database connection from client (Node01)

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner" 1>&2
   exit 1
fi


if [[ "`hostname -s`" != "node01" ]]; then
   echo "This script must be run from node01" 1>&2
   exit 1
fi

echo "Cataloging pureScale database PSDB_1 "
db2 catalog database psdb_1 as psdb_1 at node psnode

echo "Creating db2dsdriver.cfg file for PSDB_1"
cat > ~/sqllib/cfg/db2dsdriver.cfg << "EOF"
<configuration>
  <dsncollection>
    <dsn alias="PSDB_1" name="PSDB_1" host="192.168.142.102" port="50001"/>
  </dsncollection>
  <databases>
     <database name="PSDB_1" host="192.168.142.102" port="50001">
       <wlb>
          <parameter name="enableWLB" value="true"/>
       </wlb>
     </database>
  </databases>
</configuration>
EOF
