#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Catalog database connection from client (Node01)

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner" 1>&2
   exit 1
fi


if [[ "`hostname -s`" != "node01" ]]; then
   echo "This script must be run from node01" 1>&2
   exit 1
fi

echo "Cataloging TCPIP node for pureScale instance"
db2 catalog tcpip node psnode remote 192.168.142.102 server 50001 remote_instance db2sdin1
echo "Cataloging pureScale database PSDB "
db2 catalog database psdb at node psnode
