#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Run Java Program and  use client affinities

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner" 1>&2
   exit 1
fi


if [[ "`hostname -s`" != "node01" ]]; then
   echo "This script must be run from node01" 1>&2
   exit 1
fi

DEBUG=${DEBUG:=FALSE}
UOW=${UOW:=FALSE}
THREADS=${THREADS:=1}
ITERATIONS=${ITERATIONS:=1}
TPS=${TPS:=FALSE}

JAVA=$HOME/sqllib/java/jdk64/jre/bin/java
FLAGS="-DOUTPUT_DIR=./logs -Ddb2.jcc.propertiesFile=./appl14.properties"
JAR="-cp appl07.jar:$CLASSPATH"
PRG=ibm.pureScaleJavaTestProgram
COMMANDFILE=appl09.commands
APPDELAY=0
RETRY=false
LOGFILE=ps.log

$JAVA $FLAGS $JAR $PRG $DEBUG $TPS $UOW $COMMANDFILE $THREADS \
      $ITERATIONS $APPDELAY $RETRY $LOGFILE
