#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Drop db2psc instance

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

if [[ "`hostname -s`" == "node01" ]]; then
   echo "This script must be run from node02" 1>&2
   exit 1
fi

/opt/ibm/db2/instance/db2idrop -g db2psc
