--
-- Author Vikram Khatri (vikram.khatri@us.ibm.com)
-- SQL Script to find out GBP and LBP Hit Ratio
--

WITH BUFFERPOOL AS (
    SELECT BP_NAME,
           POOL_DATA_L_READS + 
           POOL_TEMP_DATA_L_READS + 
           POOL_INDEX_L_READS + 
           POOL_TEMP_INDEX_L_READS + 
           POOL_XDA_L_READS + 
           POOL_TEMP_XDA_L_READS AS LOGICAL_READS,
           POOL_DATA_P_READS + 
           POOL_TEMP_DATA_P_READS + 
           POOL_INDEX_P_READS + 
           POOL_TEMP_INDEX_P_READS + 
           POOL_XDA_P_READS + 
           POOL_TEMP_XDA_P_READS AS PHYSICAL_READS,
           POOL_ASYNC_DATA_READS + 
           POOL_ASYNC_INDEX_READS + 
           POOL_ASYNC_XDA_READS AS ASYNC_READS,
           POOL_DATA_LBP_PAGES_FOUND + 
           POOL_INDEX_LBP_PAGES_FOUND AS LBP_PAGES_FOUND,
           POOL_ASYNC_DATA_LBP_PAGES_FOUND + 
           POOL_ASYNC_INDEX_LBP_PAGES_FOUND + 
           POOL_ASYNC_XDA_LBP_PAGES_FOUND AS ASYNC_LBP_PAGES_FOUND, 
           POOL_DATA_GBP_L_READS + 
           POOL_INDEX_GBP_L_READS AS GBP_LOGICAL_READ,
           POOL_DATA_GBP_P_READS + 
           POOL_INDEX_GBP_P_READS AS GBP_PHYSICAL_READ,   
           POOL_DATA_GBP_INVALID_PAGES + 
           POOL_INDEX_GBP_INVALID_PAGES + 
           POOL_XDA_GBP_INVALID_PAGES AS INVALID_PAGES,        
           MEMBER
    FROM TABLE(MON_GET_BUFFERPOOL('',-2)) AS METRICS
    WHERE BP_NAME NOT LIKE 'IBMSYSTEM%')
SELECT
    VARCHAR(BP_NAME,20) AS BP_NAME,
    CASE WHEN LOGICAL_READS > 0 THEN 
	   DEC((1 - (FLOAT(PHYSICAL_READS - ASYNC_READS)/
	             FLOAT(LOGICAL_READS))) * 100,5,2)
    ELSE NULL
    END AS OVERALL_HR,
    CASE WHEN LOGICAL_READS > 0 THEN 
	   DEC(FLOAT(LBP_PAGES_FOUND - ASYNC_LBP_PAGES_FOUND)/
	       FLOAT(LOGICAL_READS) * 100,5,2)
    ELSE NULL
    END AS LBP_HR,
    CASE WHEN GBP_LOGICAL_READ > 0 THEN 
	  DEC(FLOAT(GBP_LOGICAL_READ - GBP_PHYSICAL_READ)/
	      FLOAT(GBP_LOGICAL_READ) * 100,5,2)
    ELSE NULL
    END AS GBP_HR,
    CASE WHEN LOGICAL_READS > FLOAT(GBP_LOGICAL_READ * 0.10) 
    THEN 'LOW' ELSE 'HIGH' END AS GBP_DPND,
    CASE WHEN INVALID_PAGES > FLOAT(GBP_LOGICAL_READ * 0.25) 
    THEN 'YES' ELSE 'NO' END AS GBP_HELP,
    MEMBER
FROM BUFFERPOOL
ORDER BY MEMBER;
