-- Author Vikram Khatri (vikram.khatri@us.ibm.com)
-- Monitor CF CPU, Memory and Swap Usage

SELECT CURRENT_TIME "TIME",
       MEMBER, 
       VARCHAR(HOST_NAME, 8)    HOST, 
       DEC(CPU_LOAD_SHORT,5,2)  CPU_SHORT, 
       DEC(CPU_LOAD_MEDIUM,5,2) CPU_MEDIUM, 
       DEC(CPU_LOAD_LONG,5,2)   CPU_LONG, 
       DEC(CPU_USAGE_TOTAL,5,2) CPU_TOTAL
FROM TABLE(SYSPROC.ENV_GET_SYSTEM_RESOURCES())
;

WITH TYPES AS (SELECT NAME FROM SYSIBMADM.ENV_CF_SYS_RESOURCES GROUP BY NAME)
SELECT A.ID, 
       SUBSTR(MIN(DECODE(T.NAME, 'HOST_NAME', A.VALUE)),1,6) HOST_NAME,
       INT(MIN(DECODE(T.NAME, 'MEMORY_TOTAL', A.VALUE)) -
       MIN(DECODE(T.NAME, 'MEMORY_FREE', A.VALUE))) MEMORY_IN_USE ,
       INT(MIN(DECODE(T.NAME, 'MEMORY_SWAP_TOTAL', A.VALUE)) -
       MIN(DECODE(T.NAME, 'MEMORY_SWAP_FREE', A.VALUE))) SWAP_IN_USE
FROM SYSIBMADM.ENV_CF_SYS_RESOURCES A, TYPES T
WHERE A.NAME = T.NAME
GROUP BY A.ID
;
