#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Stop Data Server Manager

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner and not as root" 1>&2
   exit 1
fi

if [[ "`hostname -s`" != "node01" ]]; then
   echo "This script must be run from node01" 1>&2
   exit 1
fi
OLDWD=$PWD
echo "Stopping Data Server Manager Server"
cd /home/dsm/dsm/ibm-datasrvrmgr/bin
./stop.sh
cd $OLDWD
