#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Do clean-up

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner" 1>&2
   exit 1
fi

rm -fr logs
rm -f serverlist.lock
rm -f jccdiag.log
rm -f connlicj.bin
rm -f license.lock
rm -f jccServerListCache.bin
