#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Kill CF Process on either node02 or node03

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner" 1>&2
   exit 1
fi

if [[ "$1" == "" || ("$1" != "node02" && "$1" != "node03") ]]; then
   echo Usage: $0 node02 or node03
   exit -1
fi

NODE=$1

CFPID=`ssh $NODE ps -ef | grep ca-server | grep -v ca-mgmnt | grep -v grep | awk '{print $2'}` 
if [[ $CFPID == "" ]]; then
   echo No process found for CF at $NODE
else
   echo Killing CF Process ID $CFPID on $NODE 
   ssh $NODE kill -9 $CFPID
fi

