#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Kill DB2 member on either node02 or node03 or node04

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner" 1>&2
   exit 1
fi

if [[ "$1" == "" || ("$1" != "node02" && "$1" != "node03" && "$1" != "node04"
) ]]; then
   echo Usage: $0 node02 or node03 node04
   exit -1
fi

NODE=$1

DB2PID=`ssh $NODE ps -ef | grep db2sys | grep -v idle | grep -v grep | awk '{print $2'}` 
if [[ $DB2PID == "" ]]; then
   echo DB2 Member process not found to kill on $NODE
else
  echo Killing DB2 member 0 ID $DB2PID on $NODE 
  ssh $NODE kill -9 $DB2PID
fi
