#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Start DB2 member on either node02 or node03 or node04

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner" 1>&2
   exit 1
fi

if [[ "$1" == "" || ("$1" != "node02" && "$1" != "node03" && "$1" != "node04") ]]; then
   echo Usage: $0 node02 or node03 node04
   exit -1
fi

NODE=$1
MEM=$[${NODE#node0}-2]

DB2PID=`ssh $NODE ps -ef | grep db2sys | grep -v idle | grep -v grep | awk '{print $2'}` 
if [[ $DB2PID == "" ]]; then
  echo Starting DB2 Member $MEM on $NODE
  ssh $NODE db2start member $MEM
else
  echo DB2 member $MEM already started on $NODE 
fi
