#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Clear Alerts

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner" 1>&2
   exit 1
fi

NODE=node04

echo Clearing alerts
ssh $NODE db2cluster -clear -alert
