#!/bin/bash
#
# IBM DB2 pureScale Proof of Technology
#
# Author : Vikram Khatri vikram.khatri@us.ibm.com
#
# Purpose: Recycle DB2 on all nodes

if [[ $EUID -eq 0 ]]; then
   echo "This script must be run as instance owner" 1>&2
   exit 1
fi

echo Recycling DB2
ssh node02 db2 force applications all
sleep 3
ssh node03 db2 force applications all
sleep 3
ssh node04 db2 force applications all
sleep 3
ssh node02 db2stop force
sleep 3
ssh node02 ipclean
ssh node03 ipclean
ssh node04 ipclean
ssh node02 db2start
